### ISSUE TITLE
redis.streamified is not a function

### ISSUE THREAD

**Issue by mathurs** [adriano-di-giovanni/node-redis-streamify#1]
The following code is throwing this error: TypeError: redis.streamified is not a function

var redis = require('redis');
require('node-redis-streamify')(redis); 
var scan = redis.streamified('SCAN'); // case insensitive

The version of redis I am using is 2.6.0-2. Please let me know how we can fix this.

**Comment by adriano-di-giovanni** [comment]
I'm on holiday, now. I'll be back in a few days.

Inviato da iPhone

**Comment by adriano-di-giovanni** [comment]
I updated dependencies and run the tests. Everything seems to be ok. You can clone the repo and run the tests yourself. Please, let me know if I can help you.

**Comment by mathurs** [comment]
Actually its the client which should be used

var redis = require('redis');
require('node-redis-streamify')(redis); 
var rediscl = redis.createClient();
var scan = rediscl.streamified('SCAN'); // case insensitive

This works

**Comment by jimoe** [comment]
I get the same result.  I have to use 
const redis = require('redis');
require('node-redis-streamify')(redis);
const client = redis.createClient(redisUrl);
client.streamified('SCAN');

The only thing I can see that may be of interest is that my script is run through babel
require("babel-register");
using
    "babel": "6.5.2",
    "babel-core": "6.13.2",
    "babel-preset-es2015": "6.13.2",
    "babel-preset-stage-0": "6.5.0",
    "redis": "2.6.2",

I am using node 5.12.0.  Your tests is working on the same version

**Comment by adriano-di-giovanni** [comment]
@jimoe still not working?
